
filter = ["*://*.doubleclick.net/*",
		 "*://doubleclick.net/*",
		 "*://*.googleadservices.com/*",
		 "*://googleadservices.com/*",
		 "*://*.googlesyndication.com/*",
		 "*://googlesyndication.com/*",
		 "*://*.moat.com/*",
		 "*://moat.com/*",
		 "*://*.fadspms.com/*",
		 "*://fadspms.com/*",
		 "*://*.fadskis.com/*",
		 "*://fadskis.com/*",
		 "*://*.runative-syndicate.com/*",
		 "*://runative-syndicate.com/*",
		 "*://*.fadspms.com/*",
		 "*://fadspms.com/*",
		 "*://*.la1dwne9cn5c.com/*",
		 "*://la1dwne9cn5c.com/*",
		 "*://*.14nuzznszbdp.com/*",
		 "*://14nuzznszbdp.com/*",
		 "*://*.gamers18plus.com/*",
		 "*://gamers18plus.com/*",
		 "*://*.best2019-games-web4.com/*",
		 "*://best2019-games-web4.com/*",
		 "*://*.valid-install.com/*",
		 "*://valid-install.com/*",
		 "*://*.demand.bidgear.com/*",
		 "*://demand.bidgear.com/*",
		 "*://*.koindut.com/*",
		 "*://koindut.com/*",
		 "*://*.2mdnsys.com/*",
		 "*://2mdnsys.com/*",
		 "*://*.thefashionball.com/*",
		 "*://thefashionball.com/*",
		 "*://*.cobalten.com/*",
		 "*://cobalten.com/*",
		 "*://*.native.propellerads.com/*",
		 "*://native.propellerads.com/*",
		 "*://*.www.w3.org/*",
		 "*://www.w3.org/*",
		 "*://*.consting-hancessor.com/*",
		 "*://consting-hancessor.com/*",
		 "*://*.wranjeon.xyz/*",
		 "*://wranjeon.xyz/*",
		 "*://*.myfastcdn.com/*",
		 "*://myfastcdn.com/*",
		 "*://*.my.rtmark.net/*",
		 "*://my.rtmark.net/*",
		 "*://*.native.propellerclick.com/*",
		 "*://native.propellerclick.com/*",
		 "*://*.apester.com/*",
		 "*://apester.com/*",
		 "*://*.air.tv/*",
		 "*://air.tv/*",
		 "*://*.googletagservices.com/*",
		 "*://googletagservices.com/*",
		 "*://*.pinterest.com/*",
		 "*://pinterest.com/*",
		 "*://*.s-onetag.com/*",
		 "*://s-onetag.com/*",
		 "*://*.stripe.com/*",
		 "*://stripe.com/*",
		 "*://*.wp.com/*",
		 "*://wp.com/*",
		 "*://*.zedo.com/*",
		 "*://zedo.com/*",
		 "*://cdn2.lockerdomecdn.com/*",
		 "*://*.cdn2.lockerdomecdn.com/*",
		 "*://*.taboola.com/*",
		 "*://taboola.com/*",
		 "*://elvenar/*",
		 "*://*.elvenar/*",
		 "*://*.forgeofempires.com/*",
		 "*://forgeofempires.com/*",
		 "*://sleepto.com/*",
		 "*://*.sleepto.com/*",
		 "*://rpgmasterleague.com/*",
		 "*://*.rpgmasterleague.com/*",
		 "*://*.helptochoose.com/*",
		 "*://helptochoose.com/*",
		 "*://onlinerpgmaster.com/*",
		 "*://*.onlinerpgmaster.com/*",
		 "*://*.steepto.com/*",
		 "*://steepto.com/*",
		 "*://moatads.com/*",
		 "*://*.moatads.com/*",
		 "*://*.addthisedge.com/*",
		 "*://addthisedge.com/*",
		 "*://addthis.com/*",
		 "*://*.addthis.com/*",
		 "*://*.fingahvf.top/*",
		 "*://fingahvf.top/*",
		 "*://artapeare.site/*",
		 "*://*.artapeare.site/*",
		 "*://*.boyaidare.club/*",
		 "*://boyaidare.club/*",
		 "*://errnaphim.site/*",
		 "*://*.errnaphim.site/*",
		 "*://*.doaraifa.click/*",
		 "*://doaraifa.click/*",
		 "*://yandex.ru/*",
		 "*://*.yandex.ru/*",
		 "*://*.mostviewed.xyz/*",
		 "*://mostviewed.xyz/*",
		 "*://bebereloomr.com/*",
		 "*://*.bebereloomr.com/*",
		 "*://*.mgid.com/*",
		 "*://mgid.com/*",
		 "*://obefjbb4mykw.com/*",
		 "*://*.obefjbb4mykw.com/*",
		 "*://*.ie8eamus.com/*",
		 "*://ie8eamus.com/*",
		 "*://o4uxrk33.com/*",
		 "*://*.o4uxrk33.com/*",
		 
		 ]
		 
		 
		 
		 

if(navigator.userAgent.indexOf("Chrome") != -1){
	b = chrome;
} else {
	b = firefox;
}

b.webRequest.onBeforeRequest.addListener(
	function() { return{cancel: true}; },
	{urls: filter },
	["blocking"]
);
